spring.application.name=dessert-shop

# Database properties
spring.datasource.url=jdbc:postgresql://localhost:5433/dessert_shop
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.jpa.hibernate.ddl-auto=validate

# Multipart files
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

# MVC -> REST requests
spring.mvc.hiddenmethod.filter.enabled=true